use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'PodProjectTest_Example' do

  target 'PodProjectTest_Tests' do
    inherit! :search_paths
    pod 'PodProjectTest'
    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
